//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Entry_Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entry_Form()
        {
            this.order_service = new HashSet<order_service>();
            this.order_stkitem = new HashSet<order_stkitem>();
        }
    
        public int Id { get; set; }
        public string region { get; set; }
        public string code { get; set; }

        [Required]
        [MaxLength(5)]
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public string plate_no { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string Brand { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z ]*$", ErrorMessage = "Invalid string")]
        public string Owner_name { get; set; }
        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public string phone { get; set; }
        [Required]
        public string Description { get; set; }
        public bool Status { get; set; }
        public System.DateTime date { get; set; }
        public string Alpha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_service> order_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_stkitem> order_stkitem { get; set; }
    }
}
