//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GaragedbEntities : DbContext
    {
        public GaragedbEntities()
            : base("name=GaragedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<Entry_Form> Entry_Form { get; set; }
        public virtual DbSet<recipt> recipts { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<order_service> order_service { get; set; }
        public virtual DbSet<order_stkitem> order_stkitem { get; set; }
        public virtual DbSet<service_table> service_table { get; set; }
    
        public virtual ObjectResult<get_loginDetail_Result> get_loginDetail(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_loginDetail_Result>("get_loginDetail", emailParameter, passParameter);
        }
    }
}
