//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class order_service
    {
        public int Id { get; set; }
        public bool status { get; set; }
        public int service_tableId { get; set; }
        public int Entry_FormId { get; set; }
        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public Nullable<int> quantity { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z ]*$", ErrorMessage = "Invalid string")]
        public string Assistant_Mechanic { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Entry_Form Entry_Form { get; set; }
        public virtual service_table service_table { get; set; }
    }
}
