//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.purchases = new HashSet<purchase>();
            this.order_stkitem = new HashSet<order_stkitem>();
        }
    
        public int Id { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9 ]*$", ErrorMessage = "Invalid string")]
        public string name { get; set; }
        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public double quantity { get; set; }
        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public double price { get; set; }

        [Required]
        public bool type { get; set; }
     
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public Nullable<double> buy_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_stkitem> order_stkitem { get; set; }
    }
}
