//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage_ManagementFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "please enter letters only without space")]
        public string Firstname { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "please enter letters only without space")]
        public string Lastname { get; set; }
        [EmailAddress]
        [Required]
        public string email { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "please enter letters only without space")]
        public string username { get; set; }
        [Required]
        public string password { get; set; }
        public string gender { get; set; }
        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Use numbers only please")]
        public string phone_no { get; set; }
        public string role { get; set; }
        public bool status { get; set; }
        public string ResetPasswordCode { get; set; }
    }
    public enum role
    {
      Mechanic,cashier,StockManager
    }
    public enum gender
    {
       Male,Female
    }
}
